In [21]:
# Import the random forest package
from sklearn.ensemble import RandomForestClassifier 
import numpy as np

In [50]:
import pandas as pd

titanic=pd.read_excel("titanic3.xlsx")
titanic2=titanic.fillna(titanic.mean())
X=titanic2[["age","fare"]]
y=titanic2["survived"]
#"pclass",

In [51]:
from sklearn.cross_validation import train_test_split
Xtrain, Xtest, ytrain, ytes= train_test_split(X,y,test_size=0.2)

In [49]:
X

      pclass        age      fare
0          1  29.000000  211.3375
1          1   0.916700  151.5500
2          1   2.000000  151.5500
3          1  30.000000  151.5500
4          1  25.000000  151.5500
5          1  48.000000   26.5500
6          1  63.000000   77.9583
7          1  39.000000    0.0000
8          1  53.000000   51.4792
9          1  71.000000   49.5042
10         1  47.000000  227.5250
11         1  18.000000  227.5250
12         1  24.000000   69.3000
13         1  26.000000   78.8500
14         1  80.000000   30.0000
15         1  29.881135   25.9250
16         1  24.000000  247.5208
17         1  50.000000  247.5208
18         1  32.000000   76.2917
19         1  36.000000   75.2417
20         1  37.000000   52.5542
21         1  47.000000   52.5542
22         1  26.000000   30.0000
23         1  42.000000  227.5250
24         1  29.000000  221.7792
25         1  25.000000   26.0000
26         1  25.000000   91.0792
27         1  19.000000   91.0792
28         1  35.000000  135.6333
29         1  28.000000   26.5500
...      ...        ...       ...
1279       3  14.000000    7.8542
1280       3  22.000000    7.8958
1281       3  22.000000    9.0000
1282       3  29.881135    8.0500
1283       3  29.881135    7.5500
1284       3  29.881135    8.0500
1285       3  32.500000    9.5000
1286       3  38.000000    7.2292
1287       3  51.000000    7.7500
1288       3  18.000000    6.4958
1289       3  21.000000    6.4958
1290       3  47.000000    7.0000
1291       3  29.881135    8.7125
1292       3  29.881135    7.5500
1293       3  29.881135    8.0500
1294       3  28.500000   16.1000
1295       3  21.000000    7.2500
1296       3  27.000000    8.6625
1297       3  29.881135    7.2500
1298       3  36.000000    9.5000
1299       3  27.000000   14.4542
1300       3  15.000000   14.4542
1301       3  45.500000    7.2250
1302       3  29.881135    7.2250
1303       3  29.881135   14.4583
1304       3  14.500000   14.4542
1305       3  29.881135   14.4542
1306       3  26.500000    7.2250
1307       3  27.000000    7.2250
1308       3  29.000000    7.8750

[1309 rows x 3 columns]

In [52]:
# Create the random forest object which will include all the parameters
# for the fit
forest = RandomForestClassifier(n_estimators = 1000)

In [56]:
# Fit the training data to the Survived labels and create the decision trees
forest = forest.fit(Xtrain,ytrain)

# Take the same decision trees and run it on the test data
output = forest.predict(Xtest)

In [57]:
#accuracy
float(ytes.count()-np.abs(output-ytes).sum())/ytes.count()

0.648854961832061

In [58]:
forest.feature_importances_

array([ 0.38162951,  0.61837049])